# Site settings
title: Configuración de la máquina IAAS
description: Informe de la práctica nº1 de DSI.

# Theme settings
theme: jekyll-theme-architect

# Markdown settings
markdown: kramdown

# Github Pages settings
github:
  repository: DanielFelipeGomez/temas.gitgub.io

# Build settings
permalink: /:year/:month/:day/:title/
paginate: 5
